### ISSUE TITLE
ошибка запуска дефолтного таска 'qulp'

### ISSUE THREAD

**Issue by anti-pode** [agragregra/gulp-lesson#10]
при запуске qulp вылезает следующая ошибка:
![image](https://user-images.githubusercontent.com/41538669/53691333-3c7dec00-3dae-11e9-83cd-761e01f34c03.png)

я решил это проблему, у вас в папке 'app' должна быть папка 'css' с файлом 'libs.css', а также следует указать правильный путь к jquery, либо поставить версию в которой такой путь: 'app/libs/jquery/dist/jquery.min.js'

**Comment by wdmcourses** [comment]
Урок обновлён. Читайте страницу урока.

**Comment by anti-pode** [comment]
> Урок обновлён. Читайте страницу урока.

Я это знаю, эта ошибка у меня вылезла, когда я просто скачал себе архив этого репозитория, установил node_modules в папку "gulp-4" и прописал "gulp" в консоли

**Comment by wdmcourses** [comment]
Следует скачивать master, а не первый релиз. Там всё протестировано и прекрасно работает. Релизы будут удалены.
