### ISSUE TITLE
как подтнуть все указанные пакеты разом?

### ISSUE THREAD

**Issue by VitaliyAT** [agragregra/gulp-lesson#2]
вот лежит уже ваш project.json и в нём ссылки на модули или пакеты галпа, какой командой их всех качнуть в node_modules разом... должна быть такая автоматизация иначе нонсенс получается: программа автоматизации действий сама не автоматизированна. в grunt такое есть.

**Comment by lgg** [comment]
@VitaliyAT `npm install`

Это не зависит от gulp/grunt. Файл `package.json` является файлом относящимся к npm (node packet manager).

**Comment by MoskalenkoM** [comment]
смотрите видео урока внимательней, там автор сказал как подтянуть все пакеты разом, иначе потом будут вопросы типа - "Как скачать с гитхаба ваши файлы")
